### ISSUE TITLE
Create Recipe Info Web Component

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#123]
This custom Web Component should have the html tag of `<recipe-info>` and will be rendered with a recipe's JSON using `.data`, similar to the custom web component we made in Lab 6. This `<recipe-info>` component will be placed into a `<recipe-page>` component.

The information from `.data`, (like prepTime, directions, name, rating), can be extracted in a similar manner as to how the custom web components in RecipeCard.js or RecipeExpand.js extract their recipe information from `.data`. You can also look at my code for the RecipeCard.js `<recipe-card>` I created and base it off of that. 

You can assume the `data` passed to this component will be in the same form as the `data` we obtain in the Lab 6 custom component, as well as the `data` parameter received in the `data(data)` function in the RecipeCard.js we have created so far.

This component should only concern the following portion of the figma:
![image](https://user-images.githubusercontent.com/19500878/142720411-9c62c0d3-8c9b-4d52-948c-afa4fc02160d.png)

The buttons do not need to be there yet, just the information from the recipe for now. 

Feel free to make your own components to be used for this component, e.g. a `<directions-list>` if that would be easier than just making a for loop for `<li>`.

**Comment by TuckerFrandsen** [comment]
The skeleton is complete. Needs to parse the directions more completely. Currently outputs Object, object for each step. Also need to adjust the css/styling so that each page looks correct.

**Comment by TuckerFrandsen** [comment]
Fixed the issue where directions was only showing "object, Object" but parsing that object and retrieving the actual directions text.

**Comment by mlgi** [comment]
Broke this component up into a second part so that directions can be abstracted into its own component as in issue #129 

![image](https://user-images.githubusercontent.com/19500878/142744768-9f0bbe2c-e174-45fe-b8f4-498424e845f1.png)

**Comment by TuckerFrandsen** [comment]
Added star pictures to the ratings, however the css to make them place nice with the rest of the line isn't working. Still need icons for the prep/cook time as well as buttons for ingredients/nutritions/save recipe.
