### ISSUE TITLE
Create Recipe Page Web Component

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#124]
This custom Web Component should have the tag of `<recipe-page>` and will be rendered when a `<recipe-card>` is clicked. The corresponding recipe data will be passed into this component using `.data`, similar to the web components previously done in lab 6 and the current version of our RecipeCard.js custom web component. 

The information from .data, (like prepTime, directions, name, rating), can be extracted in a similar manner as to how the custom web components in RecipeCard.js or RecipeExpand.js extract their recipe information from .data. You can also look at my code for the RecipeCard.js <recipe-card> I created and base it off of that.

You can assume the data passed to this component will be in the same form as the data we obtain in the Lab 6 custom component, as well as the data parameter received in the data(data) function in the RecipeCard.js we have created so far.

This component uses the `<recipe-info>` component and should pass the `.data` to the `<recipe-info>` component. #123
This component uses the `<ingredients-info>` component and should pass the `.data` to the `<ingredients-info>` component. #125

This component is concerned with the following portion of the figma:

![image](https://user-images.githubusercontent.com/19500878/142720668-fff31c10-2615-4aec-a257-a336f742bf79.png)

**Comment by TuckerFrandsen** [comment]
The skeleton is complete. Needs css and styling. Or let it inherit from RecipeInfo.js.
