### ISSUE TITLE
Create Ingredients Web Component

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#125]
This custom Web Component should have the html tag of `<ingredients-info>` and will be rendered when a button in `<recipe-info>` in the same `<recipe-page>` is clicked. (You don't have to bind this button yet).

`main.js` will take care of the button bindings. 

The information from .data, (like prepTime, directions, name, rating, etc), can be extracted in a similar manner as to how the custom web components in RecipeCard.js or RecipeExpand.js extract their recipe information from .data. You can also look at my code for the RecipeCard.js I created and base it off of that.

You can assume the data passed to this component will be in the same form as the data we obtain in the Lab 6 custom component, as well as the data parameter received in the data(data) function in the RecipeCard.js we have created so far.

This component is concerned with the following portion of the figma:
![image](https://user-images.githubusercontent.com/19500878/142720814-7e36f364-e448-4fa8-a28c-4090952bc587.png)

The quantity scaling and grocery cart additions can be implemented later. The important part is having a list of ingredients.

**Comment by TuckerFrandsen** [comment]
Created the skeleton for IngredientsInfo.js. The script has been added to the header part in index.html. It has not been implemented in main.js. There are no styling/css applied to it yet. There are no eventHandlers on the buttons as well.

**Comment by ctyuucsdedu** [comment]
Tucker where are you at now?

**Comment by ctyuucsdedu** [comment]
Would you mind to meet tomorrow so I could join you?
