### ISSUE TITLE
Data Scraping/Firebase Database Storage

### ISSUE THREAD

**Issue by TuckerFrandsen** [cse110-fa21-group27/cse110-fa21-group27#156]
Currently we have no database of recipe json files. We will likely need quite a few in order to correctly demonstrate searching and our "teaching map". In order to address this, work out how to run data scraping to obtain a bunch of recipes that correctly work with our page and store them, likely in Firebase so that we can access them.

**Comment by mlgi** [comment]
Decided to go with grabbing a bunch of recipes using spoonacular API as in ADR [112721-APIchoice]
