### ISSUE TITLE
Saved Recipe Page

### ISSUE THREAD

**Issue by TuckerFrandsen** [cse110-fa21-group27/cse110-fa21-group27#157]
We need a Saved Recipe Page component that the user can click on and view only the recipes they have saved. It may also be useful to create some sort of system that allows the user to create groups to sort their saved recipes. For example, they could create a Breakfast group and save a bunch of recipes into that. Miguel worked hard to get the saved recipes feature to work on the homepage, so he will have the most up-to-date knowledge about how to use that to create a page/component.

**Comment by mlgi** [comment]
really basic implementation closed by 70662b8116e3e59885c6020c8f22c37a0b8448f7 for now
