### ISSUE TITLE
Filtering/Search Page

### ISSUE THREAD

**Issue by TuckerFrandsen** [cse110-fa21-group27/cse110-fa21-group27#158]
Currently we have no search page or way for users to filter recipes. Our Miro board suggests several ways that users might like to filter recipes. Therefore, create a component for a search page and ways to filter recipes so that users can quickly and easily access the recipes they want. It might be useful to extract information about each recipe like cook time so they could filter based on that.

**Comment by mlgi** [comment]
Broken up into issues
- [ ] front-end #179 
- [ ] back-end #178

**Comment by mlgi** [comment]
Remaining feature is filtering. Front-end has the components, storage.js just needs implement the filtering.

The implementation begins in 1ca6f93bb611307157acfa72a7c15d7b50ce9681
