### ISSUE TITLE
change storage.js to support spoonacular's recipeids instead of our old recipeURLs

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#168]
## storage.js changes
- edit getRecipes()
  - should require a list of recipeids to be passed as input
  - after execution, should edit storage.recipeData to include the recipes that were "get'ed"
- create getRecipe()
  - should only take in a single recipeid to be passed as input
  - after execute, should edit storage.recipeData to include the recipe that was requested
- change getUserInfo()
  - initializing as blank user should also fill localStorage['recipes'] object with the 300 recipes
- localStorage layout
  - localStorage.recipes should be an object instead of an array
  - the keys should be the recipeids (e.g. recipes[38391] should give me the recipe object with the recipeid of 38391)

**Comment by TuckerFrandsen** [comment]
Currently working to overhaul getRecipes() to complete most of these requirements in a single function. It will populate storageRecipes and recipeData using ids.

**Comment by TuckerFrandsen** [comment]
Unsure if I still need to implement the getRecipes(list of recipeids) and getRecipe(recipeids) functions if all the population of recipeData and localStorage is done by getRecipes() with no need for input.

**Comment by mlgi** [comment]
I think we should implement getRecipes() and getRecipe() so we're not always forced to get all 7MB into memory every time. If a user is only going to their savedRecipes page, they only need to load those into memory. 

Maybe we can do a getAllRecipes() function?

**Comment by mlgi** [comment]
We can come back to that later in a separate issue. Closed by 602c6fab32bc18beb9a1433b86277a69a5875476
