### ISSUE TITLE
Recipe Collections Feature (Backend)

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#172]
# Recipe Collections Backend
**DO NOT WORK ON THIS UNTIL #170 IS COMPLETED**

The following changes need to be made/implemented:
- userInfo needs to include an array of collections
  - a collection is an object containing the following
    - collectionid - *for referencing the collection*
    - name - *collection name displayed to users*
    - ids - *an array of recipeids*
- update storage.getUserInfo()
  - when the user is first initialized (i.e. empty localStorage), we need to create an empty collection array in userInfo
- create storage.addCollection() - *creates an empty collection and updates userInfo and localStorage*
- create storage.removeCollection() - *removes a collection from userInfo and localStorage*
- create storage.addToCollection() - *given a recipeid and a collectionid, should add recipeid to the referenced collection and update userInfo/localStorage*
- create storage.removeFromCollection() - *given a recipeid and a collectionid, should remove recipeid from the referenced collection and update userInfo/localStorage*

**Comment by TuckerFrandsen** [comment]
Added collections[] to userInfo with the above mentioned properties. addCollection() and removeCollection() are implemented but untested.

**Comment by TuckerFrandsen** [comment]
addToCollection() and removeFromCollection() are implemented but untested since they are not currently used anywhere.
