### ISSUE TITLE
Search Results (Front-end)

### ISSUE THREAD

**Issue by mlgi** [cse110-fa21-group27/cse110-fa21-group27#179]
# Search Results Component 
- This component should display the search results passed into it
- `<search-results>`
- This component can be assumed to have the `renderRecipes()` function from `main.js` to be passed into it as a property, similar to how `storage.addToSavedRecipes` is passed into `<recipe-page>` and `<recipe-info>`. 
- create a `set data(data)` function
  - data parameter should be an array of recipeids
  - should use `this.renderRecipes()` to create the recipe cards and put them into a container.
# main.js
- Create a page function in `main.js`: `searchResults(results)`
  - function parameter `results` should be an array of recipeids
  - similar to `recipePage()` in `main.js`
  - should delete everything in the `<main>` tag
  - should create a `<search-results>` element and then give it the `renderRecipes()` function: `element.renderRecipes = renderRecipes`
  - should set .data to an array containing recipeids
 
By itself, this component will *not* be functional. Linking this component to the back-end is a separate issue #178
# notes
Please place your changes into the front-end branch. You can either push straight into front-end, making sure to update your local repo using `git pull` and resolving any conflicts before running `git push`. Or you can create your own branch and make a pull request into the front-end branch.

**Comment by ctyuucsdedu** [comment]
I will be hosting a zoom meeting on 11/29 at 2 pm working on this. Please join if you are able or otherwise work with some other members on different issues. Thank you.

**Comment by Steven-Christensen** [comment]
Kevin I will be working on the html elements tonight

**Comment by ctyuucsdedu** [comment]
Are you working on the /source/index.html?

**Comment by mlgi** [comment]
closed by #238
