### ISSUE TITLE
convertTime helper function - composite times or not?

### ISSUE THREAD

**Issue by ArturoAmaya** [cse110-fa21-group27/cse110-fa21-group27#183]
Currently, the convert time function successfully converts "PT2H" into "2 hr" and "PT30M" into "30 min". However, it currently cannot turn "PT2H30M" into "2hr 30 min". 

Is this is ok? If not, we should fix it to do something about it. The format is ISO8061 duration

**Comment by ArturoAmaya** [comment]
It currently turns "PT2H30M" into " 2 hr", btw

**Comment by dmcgrath19** [comment]
Hmm, I think at the least we should look into it and see if we can find a solution that converts "PT2H30M" into "2hr 30 min" and then worst case we'll figure a work around... For instance only allow recipes into our system that are whole numbers? Surely I feel as though this can be fixed though?

**Comment by mlgi** [comment]
Since we changed to spoonacular we actually don't need that helper function anymore. All their time measurements are in minutes

**Comment by ArturoAmaya** [comment]
yuppy
